apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win1
spec:
  running: false
  template:
    metadata:
      labels: 
        kubevirt.io/domain: win1
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: sata
            name: maindisk
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 4096M
      networks:
      - name: default
        pod: {}
      volumes:
      - name: maindisk
        persistentVolumeClaim:
          claimName: w2k16-g2-steve
